spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/jwtsecurity
    username: root
    password: cogent
#  flyway:  
#    url: jdbc:mysql://localhost:3306/jwtsecurity
#    user: root
#    password: cogent
#    baseline-on-migrate: true
    
    